title: Danger Cove
email: ahoy@dangercove.com
description: >- # this means to ignore newlines until "baseurl:"
  Apps you didn't know you needed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dangercove.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dangercove 
github_username:  dangercove
permalink: /news/:year/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock
