title: Danger Cove
email: ahoy@dangercove.com
description: >- # this means to ignore newlines until "baseurl:"
  Apps you didn't know you needed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dangercove.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dangercove 
github_username:  dangercove
ga_tracking_id: UA-27275793-1
permalink: /news/:year/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-archives

# Exclude from processing.
exclude:
  - deploy.sh
  - Gemfile
  - Gemfile.lock

# jekyll-assets
assets:
  sass:
    style: compressed

# Front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: []
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# jekyll-archives
jekyll-archives:
  enabled:
    - tags
  permalinks:
    tag: "/tags/:name/"
