title: Danger Cove
email: ahoy@dangercove.com
description: >- # this means to ignore newlines until "baseurl:"
  Great software for music and productivity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dangercove.com" # the base hostname & protocol for your site, e.g. http://example.com
ga_tracking_id: UA-27275793-1
permalink: /news/:title/

# Meta
logo: /assets/img/logo-256x256@2x.png
links:
  - title: Twitter
    href: https://www.twitter.com/dangercove
  - title: GitHub
    href: https://www.github.com/dangercove
  - title: YouTube
    href: https://www.youtube.com/user/DangerCove
social:
  twitter: dangercove

author:
  name: Boy van Amstel
  twitter: boyvanamstel
  href: https://www.boy.sh
  links:
    - title: Twitter
      href: https://www.twitter.com/boyvanamstel
    - title: GitHub
      href: https://www.github.com/boyvanamstel

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-archives

# Exclude from processing.
exclude:
  - LICENSE
  - README.markdown
  - deploy.sh
  - Gemfile
  - Gemfile.lock

# jekyll-assets
assets:
  sources:
    - _assets
    - _sass

# Front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: []
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# jekyll-archives
jekyll-archives:
  layout: "news/archive"
  enabled:
    - tags
  permalinks:
    tag: "/news/:name/"
