---
label: Default
hide_body: false
fields:
- type: select
  name: layout
  config:
    source:
      type: simple
    options:
    - post
    required: true
  label: Layout
  default: post
- type: text
  name: title
  label: Title
  config:
    required: false
- type: tag_list
  name: tags
  label: Tags
- type: datetime
  name: date
  label: Date
  config:
    required: false
